### ISSUE TITLE
Should permit attached_to graph to work for static models with no links

### ISSUE THREAD

**Issue by EricCousineau-TRI** [osrf/sdformat#285] opened 2020-05-16 00:03 UTC
See @scpeters's initial thoughts here:
https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/pull-requests/626/page/1#comment-127736189

**Comment by scpeters** [comment] 2020-05-28 19:20
duplicate of #282

**Closed by scpeters** 2020-05-28 19:20 UTC
